In [1]:
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.linear_model import LinearRegression

In [2]:
#reading the data
data = pd.read_excel('processed_student_data.xlsx', sheet_name='in')
data.head(5)

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0     GP   F   18       U     GT3       A     4     4   at_home   teacher   
1     GP   F   17       U     GT3       T     1     1   at_home     other   
2     GP   F   15       U     GT3       T     4     2    health  services   
3     GP   F   16       U     GT3       T     3     3     other     other   
4     GP   M   16       U     LE3       T     4     3  services     other   

   ... freetime goout  Dalc  Walc  health   absences  G1  G2  G3 sub  
0  ...        3     4     1     1       3   6.451613   5   6   6   M  
1  ...        3     3     1     1       3   4.301075   5   5   6   M  
2  ...        2     2     1     1       5   2.150538  15  14  15   M  
3  ...        3     2     1     2       5   4.301075   6  10  10   M  
4  ...        4     2     1     2       5  10.752688  15  15  15   M  

[5 rows x 34 columns]

In [3]:
#target feature
target=data['G3']
target

0       6
1       6
2      15
3      10
4      15
       ..
621    15
622    11
623    10
624    16
625    11
Name: G3, Length: 626, dtype: int64

In [ ]:
#input features
features=data[['traveltime','studytime','failures','schoolsup','famsup','paid','activities','internet','freetime','goout','Dalc','Walc','health','absences','G1','G2','sub','sex']]

In [5]:
#viewing the features data
features.head(5)

traveltime  studytime  failures schoolsup famsup paid activities internet  \
0           2          2         0       yes     no   no         no       no   
1           1          2         0        no    yes   no         no      yes   
2           1          3         0        no    yes  yes        yes      yes   
3           1          2         0        no    yes  yes         no       no   
4           1          2         0        no    yes  yes        yes      yes   

   freetime  goout  Dalc  Walc  health   absences  G1  G2 sub  
0         3      4     1     1       3   6.451613   5   6   M  
1         3      3     1     1       3   4.301075   5   5   M  
2         2      2     1     1       5   2.150538  15  14   M  
3         3      2     1     2       5   4.301075   6  10   M  
4         4      2     1     2       5  10.752688  15  15   M

In [6]:
#converting categorical to numerical one
le = LabelEncoder()
for col in ['schoolsup','famsup','paid','activities','internet','sub']:
    features[col] = le.fit_transform(features[col])

C:\Users\Sathya Rudrakshala\AppData\Local\Temp\ipykernel_51036\763329307.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features[col] = le.fit_transform(features[col])
C:\Users\Sathya Rudrakshala\AppData\Local\Temp\ipykernel_51036\763329307.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features[col] = le.fit_transform(features[col])
C:\Users\Sathya Rudrakshala\AppData\Local\Temp\ipykernel_51036\763329307.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFr

In [7]:
features.head(5)

traveltime  studytime  failures  schoolsup  famsup  paid  activities  \
0           2          2         0          1       0     0           0   
1           1          2         0          0       1     0           0   
2           1          3         0          0       1     1           1   
3           1          2         0          0       1     1           0   
4           1          2         0          0       1     1           1   

   internet  freetime  goout  Dalc  Walc  health   absences  G1  G2  sub  
0         0         3      4     1     1       3   6.451613   5   6    0  
1         1         3      3     1     1       3   4.301075   5   5    0  
2         1         2      2     1     1       5   2.150538  15  14    0  
3         0         3      2     1     2       5   4.301075   6  10    0  
4         1         4      2     1     2       5  10.752688  15  15    0

In [8]:
target.head(5)

0     6
1     6
2    15
3    10
4    15
Name: G3, dtype: int64

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    features, target, test_size=0.2, random_state=42)
linearreg=LinearRegression()

In [10]:
linearreg.fit(X_train,y_train)

LinearRegression()

In [11]:
y_pred=linearreg.predict(X_test)

In [12]:
print("R² Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

R² Score: 0.9204778651271548
MAE: 0.6465026327040776
MSE: 0.6434300426572311
RMSE: 0.802140911970728


In [13]:
# Predictions for train and test separately
y_train_pred = linearreg.predict(X_train)   
y_test_pred  = linearreg.predict(X_test)  
# Training performance
print("Train R²:", r2_score(y_train, y_train_pred))
print("Train RMSE:", np.sqrt(mean_squared_error(y_train, y_train_pred)))
# Testing performance
print("Test R²:", r2_score(y_test, y_test_pred))
print("Test RMSE:", np.sqrt(mean_squared_error(y_test, y_test_pred)))


Train R²: 0.9163511725744704
Train RMSE: 0.7845251476621409
Test R²: 0.9204778651271548
Test RMSE: 0.802140911970728


In [14]:
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix
import numpy as np
import pandas as pd

# Binary target
y_bin = (target >= 7.2).astype(int)

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
logreg = LogisticRegression(max_iter=1000, class_weight="balanced")  # handle class imbalance

# Lists to store metrics
accs_train, accs_test = [], []
precisions, recalls, f1s, aucs = [], [], [], []
conf_matrices = []

for fold, (train_idx, test_idx) in enumerate(skf.split(features, y_bin), 1):
    X_train, X_test = features.iloc[train_idx], features.iloc[test_idx]
    y_train, y_test = y_bin.iloc[train_idx], y_bin.iloc[test_idx]
    
    logreg.fit(X_train, y_train)
    y_pred_test = logreg.predict(X_test)
    y_pred_train = logreg.predict(X_train)
    y_proba_test = logreg.predict_proba(X_test)[:,1]
    
    # Train and Test Accuracy
    accs_train.append(accuracy_score(y_train, y_pred_train))
    accs_test.append(accuracy_score(y_test, y_pred_test))
    
    # Other metrics
    precisions.append(precision_score(y_test, y_pred_test))
    recalls.append(recall_score(y_test, y_pred_test))
    f1s.append(f1_score(y_test, y_pred_test))
    aucs.append(roc_auc_score(y_test, y_proba_test))
    
    # Confusion matrix
    conf_matrices.append(confusion_matrix(y_test, y_pred_test))
    print(f"\nFold {fold} Confusion Matrix:\n{conf_matrices[-1]}")

# Aggregate results
print("\n===== Logistic Regression Metrics (Stratified KFold 5) =====")
print(f"Train Accuracy: {np.mean(accs_train):.4f}")
print(f"Test Accuracy: {np.mean(accs_test):.4f}")
print(f"Precision: {np.mean(precisions):.4f}")
print(f"Recall: {np.mean(recalls):.4f}")
print(f"F1 Score: {np.mean(f1s):.4f}")
print(f"ROC-AUC: {np.mean(aucs):.4f}")



Fold 1 Confusion Matrix:
[[  2   1]
 [  3 120]]

Fold 2 Confusion Matrix:
[[  3   0]
 [  3 119]]

Fold 3 Confusion Matrix:
[[  1   2]
 [  2 120]]

Fold 4 Confusion Matrix:
[[  3   0]
 [  2 120]]

Fold 5 Confusion Matrix:
[[  1   1]
 [  0 123]]

===== Logistic Regression Metrics (Stratified KFold 5) =====
Train Accuracy: 0.9868
Test Accuracy: 0.9777
Precision: 0.9935
Recall: 0.9836
F1 Score: 0.9885
ROC-AUC: 0.9905


In [17]:
import joblib

# Save the Random Forest Regressor model
joblib.dump(linearreg, 'base_lin.pkl')
joblib.dump(logreg, 'base_log.pkl')

['base_log.pkl']

In [ ]:
print("gdfd")